---
title: "Grade Analysis Lab"
author: "Brian de Korodi"
format: html
editor: visual
keep-md: true
echo: FALSE
warning: false
---

## Question 1

```{r}
here::i_am("r-101-grade-analysis.Rproj")
here::i_am("grades.csv")
grades <- read.csv("grades.csv")
```

## Question 2

```{r}
exam_summary <-
  grades |>
  summarise("Mean grade" = mean(Exam, na.rm = TRUE),
                      "Median grade" = median(Exam, na.rm = TRUE),
                      "Lowest grade" = min(Exam, na.rm = TRUE),
                      "Highest grade" = max(Exam, na.rm = TRUE))
  
```

```{r}
knitr::kable(exam_summary, format = "markdown")
```

## Question 3

```{r}
missing_grades <- sum(is.na(grades$Exam))
```

```{r}
cat("There were", missing_grades,"students who did not take the final exam.")
```

## Question 4

```{r}
grades %>%
  ggplot(aes(x = Exam, na.rm = TRUE)) +
  geom_histogram(binwidth = 0.5, fill = "red") +
  labs(x = "Exam grades",
       y = "Frequency") +
  ggtitle("Distribution of exam grades")
```

## Question 5

```{r}
students_by_group <- 
  grades |>
  group_by(Group) |>
  summarise("Number_of_students" = n())
```

```{r}
knitr::kable(students_by_group)
```

## Question 6

```{r}
  students_by_group |>
    mutate('Group number' = gsub("grp_", "", students_by_group$Group)) |>
    ggplot(aes(x = `Group number`, y = `Number_of_students`)) +
    geom_bar(stat = "identity", fill = "red") +
    labs(title = "Number of students in each group",
         x = "Group number",
         y = "Number of students") 
```

## Question 7

```{r}
ggplot(grades, aes(x =`Exam`, fill = `Group`)) + 
  geom_density(alpha = 0.5) +
  labs(title = "Distribution of grades by group")
```

A better solution is to use a boxplot:

```{r}

```
